### ISSUE TITLE
Update mypy

### ISSUE THREAD

**Issue by abarichello** [kiwicom/dockerfiles#131]
The latest mypy tag available in your images in 0.7, mypy has since released 0.8 and 0.9 versions

https://github.com/python/mypy/releases/tag/v0.910

**Comment by aexvir** [comment]
yep, tbh we aren't using it as much internally 😅 \
but let me update it really quick 🙂

**Comment by aexvir** [comment]
updated via https://github.com/kiwicom/dockerfiles/commit/3bb757c8f959b4df37331c98924149b555843881
pushed kiwicom/mypy:0.910 but not kiwicom:mypy:latest

we have some usages of that one here and there and I don't want to break anyone's ci on a friday 😅 
will get back to it next week
