### ISSUE TITLE
Push mypy v0.8

### ISSUE THREAD

**Issue by lucasgomesdef** [kiwicom/dockerfiles#132]
Could you provide an image with v0.8 version? 

https://github.com/python/mypy/releases/tag/v0.812

**Comment by aexvir** [comment]
sure, pushed as [kiwicom/mypy:0.812](https://hub.docker.com/layers/kiwicom/mypy/0.812/images/sha256-8ae067def7ce88f50016712b7fc2c409caef45a4354cc9c0808642bc5ca8015e?context=explore)
